version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: tododook-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tododook
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: tododook-app
    depends_on:
      - mysql
    restart: always
    expose:
      - "8060"   # 호스트에 공개하지 않고 nginx가 내부에서 접근
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododook?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  nginx:
    image: nginx:latest
    container_name: tododook-nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 추가
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL 인증서 마운트
    depends_on:
      - app

volumes:
  mysql_data: