name: deploy

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: tododook-be

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker 로그인 (PAT)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: owner 소문자
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: secret 파일 생성
        run: echo "${{ secrets.APPLICATION_SECRET_YML }}" > src/main/resources/application-secret.yml

      - name: build & push
        run: |
          docker build -t ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest .
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: EC2 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/tododook
            ./deploy.sh